# Generated by Django 4.2.4 on 2023-10-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='materials_provide',
            field=models.TextField(blank=True, null=True),
        ),
    ]
